spring:
  datasource:
#    url: jdbc:postgresql://localhost:5434/inventory_db
#    username: myuser
#    password: mypassword
    url: jdbc:postgresql://alloydb-proxy:5432/inventory
    username: inventoryuser
    password: inventorypassword
    hikari:
      connection-timeout: 10000 # Increase timeout to 60 seconds
      validation-timeout: 5000  # Validation timeout
      max-lifetime: 60000       # Reduce max lifetime to avoid stale connections
      minimum-idle: 1           # Minimum idle connections
      maximum-pool-size: 10     # Maximum pool size
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml
    enabled: true

server:
  port: 8081

logging:
  level:
    root: INFO
    com.example.inventory: INFO
    liquibase: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
